"""Shared constants for the financial research app."""

APP_NAME = "Financial AI Research App"
APP_DESCRIPTION = "Educational financial research app. Not investment advice."
DEFAULT_LANGSMITH_PROJECT = "financial-langgraph-learning-app"
DEFAULT_LOOKBACK_DAYS = 30
TECHNICAL_ANALYSIS_LOOKBACK_DAYS = 180
MAX_REVIEW_ATTEMPTS = 1

CATEGORY_COMPANY_INFORMATION = "company_information"
CATEGORY_COMPETITOR_NEWS = "competitor_news"
CATEGORY_SECTOR_NEWS = "sector_news"
CATEGORY_FINANCIALS = "financials"
CATEGORY_COMPANY_NEWS = "company_news"
CATEGORY_CURRENT_STOCK_PRICE = "current_stock_price"
CATEGORY_ANALYST_RATINGS = "analyst_ratings"
CATEGORY_LATEST_REPORT_RELEASE = "latest_report_release"
CATEGORY_DOW_JONES_INDEX = "dow_jones_index"
CATEGORY_TECHNICAL_ANALYSIS = "technical_analysis"

CATEGORIES = (
    CATEGORY_COMPANY_INFORMATION,
    CATEGORY_COMPETITOR_NEWS,
    CATEGORY_SECTOR_NEWS,
    CATEGORY_FINANCIALS,
    CATEGORY_COMPANY_NEWS,
    CATEGORY_CURRENT_STOCK_PRICE,
    CATEGORY_ANALYST_RATINGS,
    CATEGORY_LATEST_REPORT_RELEASE,
    CATEGORY_DOW_JONES_INDEX,
    CATEGORY_TECHNICAL_ANALYSIS,
)

STATUS_SUCCESS = "success"
STATUS_PARTIAL = "partial"
STATUS_FAILED = "failed"

RESULT_STATUSES = (
    STATUS_SUCCESS,
    STATUS_PARTIAL,
    STATUS_FAILED,
)
